FROM ubuntu:18.04

MAINTAINER HC.yeh(hc.yeh@u-media.com.tw)



RUN apt-get update \
apt-get upgrate

RUN apt-get install build-essential cmake git pkg-config libgtk-3-dev\
libavcodec-dev libavformat-dev libswscale-dev libv4l-dev\
libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev\
gfortran openexr libatlas-base-dev python3-dev python3-numpy\
livtbb2 libtbb-dev libdc1394-22-dev

RUN mkdir ~/opencv_build && cd~/opencv_build\
git clone https://github.com/opencv/opencv.git\
git clone https://github.com/opencv/opencv_contrib.git


RUN cd ~/opencv_build/opencv\
mkdir build && cd build

RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules \
    -D BUILD_EXAMPLES=ON ..\
	make -j4\
	make install
	
RUN pkg-config --modversion opencv4

CMD["bash"]


